### ISSUE TITLE
Incompatible with OptiFabric

### ISSUE THREAD

**Issue by DNewman5** [architectury/architectury#105]
[17:48:29] [main/INFO]: Loading for game Minecraft 1.17
[17:48:30] [ForkJoinPool-1-worker-3/WARN]: Non-Fabric mod JAR at "C:\Games\Minecraft\MultiMC\instances\Fabricraft 17\.minecraft\mods\preview_OptiFine_1.17_HD_U_G9_pre18.jar", ignoring
[17:48:30] [main/INFO]: [FabricLoader] Loading 54 mods: fabric-renderer-api-v1@0.4.2+a02b4463d5, fabric-keybindings-v0@0.2.2+36b77c3ed5, fabricloader@0.11.3, fabric-structure-api-v1@1.1.10+be9da310d5, fabric-containers-v0@0.1.12+a02b4463d5, fabric-dimensions-v1@2.0.10+a02b4463d5, fabric-object-builder-api-v1@1.10.9+b7ab6121d5, java@16, fabric-game-rule-api-v1@1.0.6+a02b4463d5, fabric-api-base@0.3.0+a02b4463d5, fabric-rendering-data-attachment-v1@0.1.5+a02b4463d5, mm@2.2, fabric-textures-v0@1.0.6+a02b4463d5, fabric-rendering-fluids-v1@0.1.13+a02b4463d5, fabric-blockrenderlayer-v1@1.1.5+a02b4463d5, fabric-lifecycle-events-v1@1.4.4+a02b4463d5, fabric-renderer-registries-v1@3.2.0+a02b4463d5, fabric-loot-tables-v1@1.0.4+a02b4463d5, fabric@0.34.9+1.17, fabric-particles-v1@0.2.4+a02b4463d5, fabric-networking-v0@0.3.2+92519afad5, fabric-api-lookup-api-v1@1.0.2+a02b4463d5, fabric-networking-blockentity-v0@0.2.11+a02b4463d5, minecraft@1.17, fabric-screen-handler-api-v1@1.1.8+a02b4463d5, fabric-command-api-v1@1.1.1+a02b4463d5, cloth-basic-math@0.5.1, fabric-screen-api-v1@1.0.3+b7ab6121d5, fabric-tool-attribute-api-v1@1.2.12+b7ab6121d5, fabric-renderer-indigo@0.4.8+a02b4463d5, fabric-events-interaction-v0@0.4.8+a02b4463d5, fabric-crash-report-info-v1@0.1.5+be9da310d5, fabric-item-api-v1@1.2.4+a02b4463d5, roughlyenoughitems@6.0.249-alpha, wthit@3.5.1, fabric-entity-events-v1@1.1.0+a02b4463d5, fabric-rendering-v0@1.1.2+92519afad5, fabric-key-binding-api-v1@1.0.4+a02b4463d5, fabric-rendering-v1@1.6.0+a02b4463d5, cloth-config2@5.0.34, fabric-resource-loader-v0@0.4.7+b7ab6121d5, fabric-content-registries-v0@0.2.2+a02b4463d5, fabric-tag-extensions-v0@1.1.4+a02b4463d5, fabric-biome-api-v1@3.1.11+9e521e13d5, optifabric@1.11.1, architectury@2.0.7, fabric-commands-v0@0.2.2+92519afad5, fabric-registry-sync-v0@0.7.9+a02b4463d5, fabric-mining-levels-v0@0.1.3+92519afad5, fabric-networking-api-v1@1.0.11+b7ab6121d5, fabric-events-lifecycle-v0@0.2.1+92519afad5, fabric-item-groups-v0@0.2.10+b7ab6121d5, fabric-models-v0@0.3.0+a02b4463d5, fabric-object-builders-v0@0.7.3+a02b4463d5
[17:48:30] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Games/Minecraft/MultiMC/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[17:48:31] [main/WARN]: The requested compatibility level JAVA_16 is higher than the level supported by the active subsystem 'Knot/Fabric' which supports JAVA_14. This is not a supported configuration and instability may occur.
[17:48:31] [main/INFO]: Compatibility level set to JAVA_16
[17:48:32] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[17:48:36] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
[17:48:37] [main/FATAL]: Mixin apply failed optifabric.compat.architectury-A.mixins.json:GameRendererMixin -> net.minecraft.class_757: org.spongepowered.asm.mixin.transformer.throwables.MixinApplicatorException Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.architectury-A.mixins.json:GameRendererMixin]
org.spongepowered.asm.mixin.transformer.throwables.MixinApplicatorException: Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.architectury-A.mixins.json:GameRendererMixin]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:353) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.3.jar:0.9.2+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.11.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) [?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3229) [?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2335) [?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) [Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:518) [Optifine-mapped.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:44) [intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:349) [intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) [intermediary-minecraft-1.17-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalArgumentException: Can't find Mixin class me/shedaniel/architectury/mixin/fabric/client/MixinGameRenderer targetting net.minecraft.class_757
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.findMixin(InterceptingMixinPlugin.java:81) ~[optifabric-1.11.1.jar:?]
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.preApply(InterceptingMixinPlugin.java:50) ~[optifabric-1.11.1.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.preApply(PluginHandle.java:158) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.preApply(MixinInfo.java:1341) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.preApply(MixinTargetContext.java:1177) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:308) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	... 32 more

**Comment by MaxNeedsSnacks** [comment]
This is an issue on OptiFabric's end. They'll have to change their mixin target from `me/shedaniel/architectury/` to `dev/architectury`

**Comment by MaxNeedsSnacks** [comment]
For progress on this, see See https://github.com/Chocohead/OptiFabric/issues/238 or https://github.com/Chocohead/OptiFabric/issues/244
