### ISSUE TITLE
[1.16.5] Crash with FTBLibrary and Architectury (Forge)

### ISSUE THREAD

**Issue by FoxMcloud5655** [architectury/architectury#145]
Seems to work just fine on a client, but when run under a dedicated server, this crash happens.

FTBLibrary version: 1605.3.4-build.87
Architectury version: 1.25.36
```
Exception message: java.lang.IllegalStateException: Can't get event bus for mod 'ftblibrary' because it was not registered!
Stacktrace:
	at me.shedaniel.architectury.registry.forge.RegistriesImpl$RegistryProviderImpl.lambda$null$0(RegistriesImpl.java:83) ~[architectury:?] {re:classloading}
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_292] {}
	at me.shedaniel.architectury.registry.forge.RegistriesImpl$RegistryProviderImpl.lambda$new$1(RegistriesImpl.java:83) ~[architectury:?] {re:classloading}
	at net.minecraft.util.LazyValue.func_179281_c(SourceFile:16) ~[?:?] {re:classloading}
	at me.shedaniel.architectury.registry.forge.RegistriesImpl$RegistryProviderImpl.updateEventBus(RegistriesImpl.java:92) ~[architectury:?] {re:classloading}
	at me.shedaniel.architectury.registry.forge.RegistriesImpl$RegistryProviderImpl.get(RegistriesImpl.java:98) ~[architectury:?] {re:classloading}
	at me.shedaniel.architectury.registry.Registries.get(Registries.java:52) ~[architectury:?] {re:classloading}
	at dev.ftb.mods.ftblibrary.item.FTBLibraryItems.<clinit>(FTBLibraryItems.java:13) ~[ftblibrary:1605.3.4-build.87] {re:classloading}
	at dev.ftb.mods.ftblibrary.FTBLibrary.<init>(FTBLibrary.java:29) ~[ftblibrary:1605.3.4-build.87] {re:classloading}
	at dev.ftb.mods.ftblibrary.forge.FTBLibraryForge.<init>(FTBLibraryForge.java:12) ~[ftblibrary:1605.3.4-build.87] {re:classloading}
```

**Comment by MaxNeedsSnacks** [comment]
I'm not entirely sure whether this is on our end or on FTB Library's, however, it may be part of the weirdness mentioned in #135, so consider this issue "merged" into that one
