### ISSUE TITLE
Client crash to desktop

### ISSUE THREAD

**Issue by Steveplays28** [architectury/architectury#174]
Hi, I was playing around with TNT when the game crashed to the desktop on a singleplayer world.
This is 100% reproducible for me on Architectury `v1.28.47` & `v1.28.48`. Haven't tested any other versions of Architectury yet.

**Steps to reproduce:**
- Install any version of Fabric & Fabric API (that is compatible with the versions of Architectury that crash, see next bulletpoint)
- Install Architectury (tested `v1.28.47` & `v1.28.48`)
- Prime TNT

Server will crash right when the TNT would otherwise explode (works fine if I remove Architectury).

​<details>
<summary>Log file:</summary>

```java
[22:30:50] [Server thread/ERROR]: Critical injection failure: LVT in net/minecraft/class_1927::method_8348()V has incompatible changes at opcode 404 in callback architectury.mixins.json:MixinExplosion->@Inject::explodePost(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/util/Set;FIIIIIILjava/util/List;)V from mod architectury.
 Expected: [Ljava/util/Set;, F, I, I, I, I, I, I, Ljava/util/List;]
    Found: [Ljava/util/Set;, I, F, I, I, I, I, I, I]
Available: [Ljava/util/Set;, I, F, I, I, I, I, I, I, Ljava/util/List;]
[22:30:50] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) [client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) [client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$4493/0x000000008ca68e70.run(Unknown Source) [client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1927 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_3218.method_8454(class_3218.java:1030) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8437(class_1937.java:573) ~[client-intermediary.jar:?]
	at net.minecraft.class_1541.method_6971(class_1541.java:100) ~[client-intermediary.jar:?]
	at net.minecraft.class_1541.method_5773(class_1541.java:88) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:621) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218$$Lambda$4800/0x000000008cd43c50.accept(Unknown Source) ~[?:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:561) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:411) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[client-intermediary.jar:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_3218.method_8454(class_3218.java:1030) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8437(class_1937.java:573) ~[client-intermediary.jar:?]
	at net.minecraft.class_1541.method_6971(class_1541.java:100) ~[client-intermediary.jar:?]
	at net.minecraft.class_1541.method_5773(class_1541.java:88) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:621) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218$$Lambda$4800/0x000000008cd43c50.accept(Unknown Source) ~[?:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:561) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:411) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[client-intermediary.jar:?]
	... 6 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_1927::method_8348()V has incompatible changes at opcode 404 in callback architectury.mixins.json:MixinExplosion->@Inject::explodePost(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/util/Set;FIIIIIILjava/util/List;)V from mod architectury.
 Expected: [Ljava/util/Set;, F, I, I, I, I, I, I, Ljava/util/List;]
    Found: [Ljava/util/Set;, I, F, I, I, I, I, I, I]
Available: [Ljava/util/Set;, I, F, I, I, I, I, I, I, Ljava/util/List;]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:545) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:495) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1374) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraft.class_3218.method_8454(class_3218.java:1030) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8437(class_1937.java:573) ~[client-intermediary.jar:?]
	at net.minecraft.class_1541.method_6971(class_1541.java:100) ~[client-intermediary.jar:?]
	at net.minecraft.class_1541.method_5773(class_1541.java:88) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:621) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218$$Lambda$4800/0x000000008cd43c50.accept(Unknown Source) ~[?:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:561) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:411) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[client-intermediary.jar:?]
	... 6 more
[22:30:50] [Server thread/ERROR]: This crash report has been saved to: C:\Program Files\MultiMC\instances\1.16.5\.minecraft\crash-reports\crash-2022-01-06_22.30.50-server.txt
[22:30:50] [Server thread/INFO]: Stopping server
[22:30:50] [Server thread/INFO]: Saving players
```

Yes, I use MultiMC.

</details>

**Comment by DX493** [comment]
Same issue with creeper / explosion.
1.27.46 & under crash too but .. 1.26.42 is fine.

**Comment by MaxNeedsSnacks** [comment]
See FabricMC/Mixin#80, we're currently waiting for an update to Fabric Loader

**Comment by Steveplays28** [comment]
Cool, thanks.

**Comment by shedaniel** [comment]
The fix to the mixin issue is now in Fabric Loader 0.13.0, you can try it out + a new architectury api version, thanks!

**Comment by Steveplays28** [comment]
Thanks @shedaniel, appreciate it! :D
