### ISSUE TITLE
[Bug] Server cannot post server messages

### ISSUE THREAD

**Issue by LunafeyLazuli** [architectury/architectury#179]
So on my server I have warnings set up to warn everyone when the server is about to go down for it's daily restarts, but the server hasn't been able to post the messages and anything with /say doesn't work either, here's the console log

[19.01 18:10:00] [Server] [Server thread/ERROR]: Exception caught during firing event: Cannot invoke "net.minecraft.world.entity.Entity.m_142081_()" because the return value of "net.minecraft.commands.CommandSourceStack.m_81373_()" is null
[19.01 18:10:00] [Server] 	Index3
[19.01 18:10:00] [Server] 	Listeners:
[19.01 18:10:00] [Server] 		HIGH
[19.01 18:10:00] [Server] 		ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/CommandEvent;)V
[19.01 18:10:00] [Server] 		NORMAL
[19.01 18:10:00] [Server] 		ASM: de.erdbeerbaerlp.dcintegration.forge.DiscordIntegration@681c0f0a command(Lnet/minecraftforge/event/CommandEvent;)V
[19.01 18:10:00] [Server] 		ASM: com.natamus.starterkit.events.FirstSpawnEvent@7e193457 onCommand(Lnet/minecraftforge/event/CommandEvent;)V
[19.01 18:10:00] [Server] java.lang.NullPointerExceptionCannot invoke "net.minecraft.world.entity.Entity.m_142081_()" because the return value of "net.minecraft.commands.CommandSourceStack.m_81373_()" is null
[19.01 18:10:00] [Server] 	at TRANSFORMER/dcintegration@2.3.5/de.erdbeerbaerlp.dcintegration.forge.DiscordIntegration.command(DiscordIntegration.java:242)
[19.01 18:10:00] [Server] 	at net.minecraftforge.eventbus.ASMEventHandler_625_DiscordIntegration_command_CommandEvent.invoke(.dynamic)
[19.01 18:10:00] [Server] 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[19.01 18:10:00] [Server] 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[19.01 18:10:00] [Server] 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[19.01 18:10:00] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.commands.Commands.m_82117_(Commands.java:224)
[19.01 18:10:00] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.dedicated.DedicatedServer.m_139665_(DedicatedServer.java:343)
[19.01 18:10:00] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:329)
[19.01 18:10:00] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808)
[19.01 18:10:00] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668)
[19.01 18:10:00] [Server] 	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
[19.01 18:10:00] [Server] 	at java.base/java.lang.Thread.run(Thread.java:833)
[19.01 18:10:00] [Server] [Server thread/INFO]: An unexpected error occurred trying to execute that command

**Comment by LunafeyLazuli** [comment]
Almost forgot, architectury-3.4.9.jar is what we're using for 1.18.1

**Comment by MaxNeedsSnacks** [comment]
Please provide a full log file rather than just a snippet if you can next time, also, this is almost definitely an issue with your Discord Integration mod, and not Architectury
