### ISSUE TITLE
Reopening Crash Report for v3.7.2

### ISSUE THREAD

**Issue by VWRhyme** [architectury/architectury#206]
Maybe you misunderstood me. It crashes my Minecraft game without an explanation at all. Just says game crashed on launch. I’ll send screenshots but there’s zero explanation as to why. There’s no new update listed. So unsure as to what fix you have listed as there was no explanation given.

**Comment by VWRhyme** [comment]
![02AF175E-7703-4B7F-8D0C-3FBACA8D92CF](https://user-images.githubusercontent.com/71048393/154808978-c95240ce-9334-482b-8310-4a296c2ea9de.jpeg)
![3BC3D3D6-31C4-44A5-8636-CC7F2BB650DD](https://user-images.githubusercontent.com/71048393/154808984-9af5f984-7a4b-4931-b2ea-e00b4a695977.jpeg)

running without Achitectury to prove it opens.

**Comment by VWRhyme** [comment]
![image](https://user-images.githubusercontent.com/71048393/154809043-a8620afb-b977-4300-81ad-2d6c3976589b.jpg)
Running with v3.4.9

**Comment by VWRhyme** [comment]
![image](https://user-images.githubusercontent.com/71048393/154809104-83fbcf00-4c2d-41be-9d42-a41df4c2cfd3.jpg)
Crash with v3.7.2 no explanation given just JavaRuntime configuration. I have not changed anything between the two at all.

**Comment by Juuxel** [comment]
Please post your game logs (which are always more useful than crash reports in the first place), there's nothing we can do otherwise

**Comment by VWRhyme** [comment]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded IllegalStateException whilst transforming the mixin class: [PostApply Phase -> optifabric.compat.architectury-AB.newer-mixins.json:GameRendererNewerMixin -> Plugin Post-Application]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.postApply(MixinTargetContext.java:1287) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:344) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:297) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.13.2-1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.2.jar:?]
	... 2 more

**Comment by triphora** [comment]
Fixed in #203, can be closed :wink:

**Comment by Juuxel** [comment]
This is an issue with Optifine and Optifabric breaking Architectury, and we don't support the use of those mods.

**Comment by VWRhyme** [comment]
Okay can you explain to me as to why 3.7.2 breaks with optifabric/optifine and you guys are saying that you won’t fix the issue? v3.4.9 clearly works with the updated fabric mods. So I don’t understand how this is an issue for Optifabric/Optifine but Achitectury itself hence the ticket. Without Achitectury my entire mod list is practically useless which really is upsetting and I’m sure other people feel the same way as most of your quality of Minecraft life mods require Achitectury to run.

**Comment by Juuxel** [comment]
Optifabric has compatibility hacks to make Optifine and Arch API compatible that modify Arch API's internal code (which should not be touched by other mods). Since we changed the code in Arch API, Optifabric breaks with newer versions of Arch API and we can't do anything about that. See https://github.com/Chocohead/OptiFabric/issues/598
