### ISSUE TITLE
Crash in Forge MDK

### ISSUE THREAD

**Issue by shimizu-izumi** [architectury/architectury#207]
I made a mod that uses Architectury and it's used by another mod I'm making and when I try to launch Minecraft in the MDK with Architectury installed I get this error

`[21Feb.2022 15:54:38.561] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed architectury-common.mixins.json:FluidTagsAccessor -> net.minecraft.tags.FluidTags: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching f_13130_:Lnet/minecraft/tags/StaticTagHelper; in net/minecraft/tags/FluidTags for architectury-common.mixins.json:FluidTagsAccessor->@Accessor[FIELD_GETTER]::getHelper()Lnet/minecraft/tags/StaticTagHelper; [INJECT Applicator Phase -> architectury-common.mixins.json:FluidTagsAccessor -> Apply Accessors ->  -> Locate -> architectury-common.mixins.json:FluidTagsAccessor->@Accessor[FIELD_GETTER]::getHelper()Lnet/minecraft/tags/StaticTagHelper;]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching f_13130_:Lnet/minecraft/tags/StaticTagHelper; in net/minecraft/tags/FluidTags for architectury-common.mixins.json:FluidTagsAccessor->@Accessor[FIELD_GETTER]::getHelper()Lnet/minecraft/tags/StaticTagHelper; [INJECT Applicator Phase -> architectury-common.mixins.json:FluidTagsAccessor -> Apply Accessors ->  -> Locate -> architectury-common.mixins.json:FluidTagsAccessor->@Accessor[FIELD_GETTER]::getHelper()Lnet/minecraft/tags/StaticTagHelper;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1389) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1060) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:398) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.1.0.jar:9.1.0+9.1.0+main.6690ee51]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.0.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.0.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-1.0.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.level.material.Fluid.<init>(Fluid.java:100) ~[forge-1.18.1-39.0.79_mapped_parchment_2022.02.13-1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.world.level.material.EmptyFluid.<init>(EmptyFluid.java:15) ~[forge-1.18.1-39.0.79_mapped_parchment_2022.02.13-1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.world.level.material.Fluids.<clinit>(Fluids.java:6) ~[forge-1.18.1-39.0.79_mapped_parchment_2022.02.13-1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:66) ~[forge-1.18.1-39.0.79_mapped_parchment_2022.02.13-1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.world.level.levelgen.carver.CarverDebugSettings.<clinit>(CarverDebugSettings.java:9) ~[forge-1.18.1-39.0.79_mapped_parchment_2022.02.13-1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.world.level.levelgen.carver.CarverConfiguration.lambda$static$5(CarverConfiguration.java:19) ~[forge-1.18.1-39.0.79_mapped_parchment_2022.02.13-1.18.1-recomp.jar%2377!/:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar%2343!/:?]
	at net.minecraft.world.level.levelgen.carver.CarverConfiguration.<clinit>(CarverConfiguration.java:12) ~[forge-1.18.1-39.0.79_mapped_parchment_2022.02.13-1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.world.level.levelgen.carver.WorldCarver.<clinit>(WorldCarver.java:28) ~[forge-1.18.1-39.0.79_mapped_parchment_2022.02.13-1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.data.worldgen.Carvers.<clinit>(Carvers.java:18) ~[forge-1.18.1-39.0.79_mapped_parchment_2022.02.13-1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.data.BuiltinRegistries.lambda$static$0(BuiltinRegistries.java:38) ~[forge-1.18.1-39.0.79_mapped_parchment_2022.02.13-1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.data.BuiltinRegistries.lambda$static$3(BuiltinRegistries.java:111) ~[forge-1.18.1-39.0.79_mapped_parchment_2022.02.13-1.18.1-recomp.jar%2377!/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:110) ~[forge-1.18.1-39.0.79_mapped_parchment_2022.02.13-1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:536) ~[forge-1.18.1-39.0.79_mapped_parchment_2022.02.13-1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:49) ~[forge-1.18.1-39.0.79_mapped_parchment_2022.02.13-1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:138) ~[forge-1.18.1-39.0.79_mapped_parchment_2022.02.13-1.18.1-recomp.jar%2377!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by Juuxel** [comment]
If you're using ForgeGradle, this might help: https://docs.architectury.dev/docs/forge_loom/fg_broken_refmap
