### ISSUE TITLE
fabric. installed architectury but mods still cannot find it

### ISSUE THREAD

**Issue by jilotta** [architectury/architectury#227]
```
Picked up _JAVA_OPTIONS: 
[21:13:47] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[21:13:47] [main/WARN]: Mod resolution failed
[21:13:47] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE indicatia 6.0.0 {depends architectury @ [>=3.0]}, ROOT_FORCELOAD_SINGLE indicatia 6.0.0]
[21:13:47] [main/INFO]: Reason: [HARD_DEP indicatia 6.0.0 {depends architectury @ [>=3.0]}, HARD_DEP stevekung_lib 6.0.0 {depends architectury @ [>=3.0]}]
[21:13:47] [main/INFO]: Fix: add [add:architectury 3.0 ([[3.0,∞)])], remove [], replace []
[21:13:47] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install architectury, version 3.0 or later.
Unmet dependency listing:
	 - Mod 'Indicatia' (indicatia) 6.0.0 requires version 3.0 or later of architectury, which is missing!
	 - Mod 'SteveKunG's Lib' (stevekung_lib) 6.0.0 requires version 3.0 or later of architectury, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
```
Screenshot: 
![image](https://user-images.githubusercontent.com/70760350/159768930-651e1e18-3760-4a6c-8a6a-8711c579106b.png)

**Comment by ghost** [comment]
Looks like you have the forge version, try this one (for fabric): https://www.curseforge.com/minecraft/mc-mods/architectury-fabric/files/3705894

**Comment by shedaniel** [comment]
Closing this as this seems to be user error
