### ISSUE TITLE
Failed to load correctly

### ISSUE THREAD

**Issue by FireTomca** [architectury/architectury#232]
Using Mohist server, it can't load normally. 
**Error:**
-- MOD architectury --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at java.lang.Class.forName0(Native Method) ~[?:?] {}
		at java.lang.Class.forName(Unknown Source) ~[?:?] {}
		at com.sun.proxy.$Proxy28.<clinit>(Unknown Source) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {re:classloading,re:classloading}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {re:classloading,re:classloading}
		at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Proxy.newProxyInstance(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Proxy.newProxyInstance(Unknown Source) ~[?:?] {}
		at me.shedaniel.architectury.event.EventFactory.lambda$createInteractionResult$2(EventFactory.java:99) ~[architectury:?] {re:classloading}
		at me.shedaniel.architectury.event.EventFactory$EventImpl.update(EventFactory.java:369) ~[architectury:?] {re:classloading}
		at me.shedaniel.architectury.event.EventFactory$EventImpl.invoker(EventFactory.java:335) ~[architectury:?] {re:classloading}
		at me.shedaniel.architectury.event.EventHandler.registerDelegates(EventHandler.java:68) ~[architectury:?] {re:classloading,pl:runtimedistcleaner:A}
		at me.shedaniel.architectury.event.EventHandler.init(EventHandler.java:46) ~[architectury:?] {re:classloading,pl:runtimedistcleaner:A}
		at me.shedaniel.architectury.forge.ArchitecturyForge.<init>(ArchitecturyForge.java:33) ~[architectury:?] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {re:classloading,re:classloading}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {re:classloading,re:classloading}
		at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
		at java.lang.Class.newInstance(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:82) ~[forge:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

	Mod File: architectury-1.30.55.jar
	Failure message: Architectury (architectury) has failed to load correctly
		java.lang.ExceptionInInitializerError: null
	Mod Version: 1.30.55
	Mod Issue URL: https://github.com/shedaniel/architectury/issues
	Exception message: java.lang.NullPointerException
Stacktrace:
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1572) ~[asm-9.1.jar:9.1] {}
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546) ~[asm-9.1.jar:9.1] {}
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769) ~[asm-tree-9.1.jar:9.1] {}
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649) ~[asm-tree-9.1.jar:9.1] {}
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452) ~[asm-tree-9.1.jar:9.1] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:133) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at net.minecraft.entity.Entity.<clinit>(Entity.java:211) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.collision.MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Class.forName0(Native Method) ~[?:?] {}
	at java.lang.Class.forName(Unknown Source) ~[?:?] {}
	at com.sun.proxy.$Proxy28.<clinit>(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Proxy.newProxyInstance(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Proxy.newProxyInstance(Unknown Source) ~[?:?] {}
	at me.shedaniel.architectury.event.EventFactory.lambda$createInteractionResult$2(EventFactory.java:99) ~[architectury:?] {re:classloading}
	at me.shedaniel.architectury.event.EventFactory$EventImpl.update(EventFactory.java:369) ~[architectury:?] {re:classloading}
	at me.shedaniel.architectury.event.EventFactory$EventImpl.invoker(EventFactory.java:335) ~[architectury:?] {re:classloading}
	at me.shedaniel.architectury.event.EventHandler.registerDelegates(EventHandler.java:68) ~[architectury:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.architectury.event.EventHandler.init(EventHandler.java:46) ~[architectury:?] {re:classloading,pl:runtimedistcleaner:A}
	at me.shedaniel.architectury.forge.ArchitecturyForge.<init>(ArchitecturyForge.java:33) ~[architectury:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {re:classloading,re:classloading,re:classloading}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:82) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

**Comment by triphora** [comment]
We do not support any of the weird bukkit amalgamations
