### ISSUE TITLE
Fabric API incompatibility 

### ISSUE THREAD

**Issue by SylisMC** [architectury/architectury#238]
Minecraft 1.18.2
architectury-4.1.44.jar
fabric-api-0.48.0+1.18.2.jar

```Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric API' (fabric) 0.48.0+1.18.2 with version 0.50.0 or later.
Unmet dependency listing:
	 - Mod 'Architectury' (architectury) 4.1.44 requires version 0.50.0 or later of mod 'Fabric API' (fabric), but only the wrong version is present: 0.48.0+1.18.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)```

**Comment by SylisMC** [comment]
(Downgrading to  architectury-4.1.41.jar resolves the issue

**Comment by triphora** [comment]
You need to update Fabric API to 0.50.0
https://modrinth.com/mod/fabric-api/version/0.50.0+1.18.2
https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3743847

**Comment by SylisMC** [comment]
Fabric API 0.50.0 is a beta version, and its not recommended
![image](https://user-images.githubusercontent.com/19602662/162639451-99356fcc-ca14-4d1c-bf15-582007c2f3b3.png)
