### ISSUE TITLE
Failed to obtain root directory for mod 'architectury'

### ISSUE THREAD

**Issue by bundas117** [architectury/architectury#258]
Hi! I'm someone pretty inept when it comes to mods, I recently tried updating my mods to 1.18.2 after not having any issues with doing it for 1.18.1 and not sure if I messed it up somehow. Just dragged them into the mods folder but not sure if there's anything else I needed to do for it. 

Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to obtain root directory for mod 'architectury'!
	at net.fabricmc.loader.impl.ModContainerImpl.obtainRootPaths(ModContainerImpl.java:148)
	at net.fabricmc.loader.impl.ModContainerImpl.getRootPaths(ModContainerImpl.java:100)
	at net.fabricmc.loader.api.ModContainer.findPath(ModContainer.java:62)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:481)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:145)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.io.IOException: Error accessing file:///C:/Users/me/AppData/Roaming/.minecraft/mods/Architectury-API-Mod-Fabric-1.18.2.jar: java.util.zip.ZipException: zip END header not found
	at net.fabricmc.loader.impl.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:83)
	at net.fabricmc.loader.impl.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:59)
	at net.fabricmc.loader.impl.ModContainerImpl.obtainRootPath(ModContainerImpl.java:156)
	at net.fabricmc.loader.impl.ModContainerImpl.obtainRootPaths(ModContainerImpl.java:137)
	... 6 more
Caused by: java.util.zip.ZipException: zip END header not found
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1315)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1529)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:174)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
	at net.fabricmc.loader.impl.util.FileSystemUtil.getJarFileSystem(FileSystemUtil.java:78)
	... 9 more

**Comment by shedaniel** [comment]
Please download Architectury from CurseForge
