### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by nba2k23** [architectury/architectury#259]
I'm getting the error:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install architectury, version 2- or later.
Unmet dependency listing:
	 - Mod 'Light Overlay' (lightoverlay) 6.0.5 requires version 2- or later of architectury, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Although I already have architectury-4.4.60 installed via the curseforge.
Not sure what to do now..

**Comment by triphora** [comment]
I can guarantee that your issue is that you installed the Forge version instead of the Fabric version.

[Latest Fabric version](https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/3786590).
