### ISSUE TITLE
It keeps crashing 

### ISSUE THREAD

**Issue by KstarMillion** [architectury/architectury#265]
I do not get any info but an exit code 1

**Comment by Juuxel** [comment]
Can you post the full game log from `logs/latest.log` in your Minecraft instance folder?

**Comment by KstarMillion** [comment]
[24May2022 15:22:55.540] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, King_Million, --version, 1.18.2-forge-40.1.0, --gameDir, C:\Users\Kaiden Small\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Kaiden Small\AppData\Roaming\.minecraft\assets, --assetIndex, 1.18, --uuid, a059582ea935431faf25a7085267a45c, --accessToken, ????????, --clientId, ZTI1Y2JhMDQtYmUzYy00ZDM5LTk4ZjEtYTI1OGM0MDY3N2Zh, --xuid, 2535467421035533, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.0, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[24May2022 15:22:55.551] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
[24May2022 15:22:55.896] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Kaiden%20Small/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[24May2022 15:22:58.137] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing mandatory dependencies: minecraft
[24May2022 15:23:02.909] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[24May2022 15:23:03.062] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.18.2-forge-40.1.0, --gameDir, C:\Users\Kaiden Small\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Kaiden Small\AppData\Roaming\.minecraft\assets, --uuid, a059582ea935431faf25a7085267a45c, --username, King_Million, --assetIndex, 1.18, --accessToken, ????????, --clientId, ZTI1Y2JhMDQtYmUzYy00ZDM5LTk4ZjEtYTI1OGM0MDY3N2Zh, --xuid, 2535467421035533, --userType, msa, --versionType, release]
[24May2022 15:23:03.816] [main/WARN] [mixin/]: Error loading class: me/cominixo/betterf3/modules/TargetModule (java.lang.ClassNotFoundException: me.cominixo.betterf3.modules.TargetModule)
[24May2022 15:23:03.817] [main/WARN] [mixin/]: @Mixin target me.cominixo.betterf3.modules.TargetModule was not found securitycraft.mixins.json:f3.BetterF3TargetModuleMixin
[24May2022 15:23:04.882] [main/WARN] [mixin/]: Error loading class: net/minecraft/entity/ai/brain/schedule/Activity (java.lang.ClassNotFoundException: net.minecraft.entity.ai.brain.schedule.Activity)
[24May2022 15:23:04.883] [main/WARN] [mixin/]: @Mixin target net.minecraft.entity.ai.brain.schedule.Activity was not found mca.mixin.json:MixinActivity
[24May2022 15:23:04.884] [main/WARN] [mixin/]: Error loading class: net/minecraft/entity/passive/horse/AbstractHorseEntity (java.lang.ClassNotFoundException: net.minecraft.entity.passive.horse.AbstractHorseEntity)
[24May2022 15:23:04.887] [main/WARN] [mixin/]: @Mixin target net.minecraft.entity.passive.horse.AbstractHorseEntity was not found mca.mixin.json:MixinHorseBaseEntity
[24May2022 15:23:04.888] [main/WARN] [mixin/]: Error loading class: net/minecraft/entity/ai/brain/memory/MemoryModuleType (java.lang.ClassNotFoundException: net.minecraft.entity.ai.brain.memory.MemoryModuleType)
[24May2022 15:23:04.889] [main/WARN] [mixin/]: @Mixin target net.minecraft.entity.ai.brain.memory.MemoryModuleType was not found mca.mixin.json:MixinMemoryModuleType
[24May2022 15:23:04.890] [main/WARN] [mixin/]: Error loading class: net/minecraft/entity/player/PlayerEntity (java.lang.ClassNotFoundException: net.minecraft.entity.player.PlayerEntity)
[24May2022 15:23:04.892] [main/WARN] [mixin/]: @Mixin target net.minecraft.entity.player.PlayerEntity was not found mca.mixin.json:MixinPlayerEntity
[24May2022 15:23:04.893] [main/WARN] [mixin/]: Error loading class: net/minecraft/world/chunk/ChunkPrimer (java.lang.ClassNotFoundException: net.minecraft.world.chunk.ChunkPrimer)
[24May2022 15:23:04.895] [main/WARN] [mixin/]: @Mixin target net.minecraft.world.chunk.ChunkPrimer was not found mca.mixin.json:MixinProtoChunk
[24May2022 15:23:04.896] [main/WARN] [mixin/]: Error loading class: net/minecraft/entity/ai/brain/sensor/SensorType (java.lang.ClassNotFoundException: net.minecraft.entity.ai.brain.sensor.SensorType)
[24May2022 15:23:04.898] [main/WARN] [mixin/]: @Mixin target net.minecraft.entity.ai.brain.sensor.SensorType was not found mca.mixin.json:MixinSensorType
[24May2022 15:23:04.901] [main/WARN] [mixin/]: Error loading class: net/minecraft/world/server/ServerWorld (java.lang.ClassNotFoundException: net.minecraft.world.server.ServerWorld)
[24May2022 15:23:04.901] [main/WARN] [mixin/]: @Mixin target net.minecraft.world.server.ServerWorld was not found mca.mixin.json:MixinServerWorld
[24May2022 15:23:04.903] [main/WARN] [mixin/]: Error loading class: net/minecraft/entity/EntityPredicate (java.lang.ClassNotFoundException: net.minecraft.entity.EntityPredicate)
[24May2022 15:23:04.904] [main/WARN] [mixin/]: @Mixin target net.minecraft.entity.EntityPredicate was not found mca.mixin.json:MixinTargetPredicate
[24May2022 15:23:04.910] [main/WARN] [mixin/]: Error loading class: net/minecraft/entity/merchant/villager/VillagerEntity (java.lang.ClassNotFoundException: net.minecraft.entity.merchant.villager.VillagerEntity)
[24May2022 15:23:04.910] [main/WARN] [mixin/]: @Mixin target net.minecraft.entity.merchant.villager.VillagerEntity was not found mca.mixin.json:MixinVillagerEntity
[24May2022 15:23:04.911] [main/WARN] [mixin/]: Error loading class: net/minecraft/entity/monster/ZombieVillagerEntity (java.lang.ClassNotFoundException: net.minecraft.entity.monster.ZombieVillagerEntity)
[24May2022 15:23:04.911] [main/WARN] [mixin/]: @Mixin target net.minecraft.entity.monster.ZombieVillagerEntity was not found mca.mixin.json:MixinZombieVillagerEntity
[24May2022 15:23:04.916] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/network/play/ClientPlayNetHandler (java.lang.ClassNotFoundException: net.minecraft.client.network.play.ClientPlayNetHandler)
[24May2022 15:23:04.917] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.network.play.ClientPlayNetHandler was not found mca.mixin.json:MixinClientPlayNetworkHandler
[24May2022 15:23:04.917] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/entity/player/ClientPlayerEntity (java.lang.ClassNotFoundException: net.minecraft.client.entity.player.ClientPlayerEntity)
[24May2022 15:23:04.920] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.entity.player.ClientPlayerEntity was not found mca.mixin.json:client.MixinClientPlayerEntity
[24May2022 15:23:04.921] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/gui/FontRenderer (java.lang.ClassNotFoundException: net.minecraft.client.gui.FontRenderer)
[24May2022 15:23:04.921] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.gui.FontRenderer was not found mca.mixin.json:client.MixinTextRenderer
[24May2022 15:23:04.922] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/resources/ClientLanguageMap (java.lang.ClassNotFoundException: net.minecraft.client.resources.ClientLanguageMap)
[24May2022 15:23:04.922] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.resources.ClientLanguageMap was not found mca.mixin.json:client.MixinTranslationStorage
[24May2022 15:23:10.182] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed architectury.mixins.json:MixinBlockEntity -> net.minecraft.world.level.block.entity.BlockEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on getUpdatePacket could not find any targets matching 'Lnet/minecraft/world/level/block/entity/BlockEntity;m_7033_()Lnet/minecraft/network/protocol/game/ClientboundBlockEntityDataPacket;' in net.minecraft.world.level.block.entity.BlockEntity. Using refmap architectury-forge-refmap.json [PREINJECT Applicator Phase -> architectury.mixins.json:MixinBlockEntity -> Prepare Injections ->  -> handler$zzj000$getUpdatePacket(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on getUpdatePacket could not find any targets matching 'Lnet/minecraft/world/level/block/entity/BlockEntity;m_7033_()Lnet/minecraft/network/protocol/game/ClientboundBlockEntityDataPacket;' in net.minecraft.world.level.block.entity.BlockEntity. Using refmap architectury-forge-refmap.json [PREINJECT Applicator Phase -> architectury.mixins.json:MixinBlockEntity -> Prepare Injections ->  -> handler$zzj000$getUpdatePacket(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at jdk.internal.reflect.GeneratedConstructorAccessor59.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.1.3.jar:9.1.3+9.1.3+main.9b69c82a]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:118) ~[client-1.18.2-20220404.173914-srg.jar%2366!/:?]
	at net.minecraft.world.level.levelgen.carver.CarverDebugSettings.<clinit>(CarverDebugSettings.java:9) ~[client-1.18.2-20220404.173914-srg.jar%2366!/:?]
	at net.minecraft.world.level.levelgen.carver.CarverConfiguration.m_190634_(CarverConfiguration.java:16) ~[client-1.18.2-20220404.173914-srg.jar%2366!/:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.1.27.jar%2333!/:?]
	at net.minecraft.world.level.levelgen.carver.CarverConfiguration.<clinit>(CarverConfiguration.java:12) ~[client-1.18.2-20220404.173914-srg.jar%2366!/:?]
	at net.minecraft.world.level.levelgen.carver.WorldCarver.<clinit>(WorldCarver.java:30) ~[client-1.18.2-20220404.173914-srg.jar%2366!/:?]
	at net.minecraft.data.worldgen.Carvers.<clinit>(Carvers.java:19) ~[client-1.18.2-20220404.173914-srg.jar%2366!/:?]
	at net.minecraft.data.BuiltinRegistries.m_206400_(BuiltinRegistries.java:45) ~[client-1.18.2-20220404.173914-srg.jar%2366!/:?]
	at net.minecraft.data.BuiltinRegistries.m_206392_(BuiltinRegistries.java:101) ~[client-1.18.2-20220404.173914-srg.jar%2366!/:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:100) ~[client-1.18.2-20220404.173914-srg.jar%2366!/:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:633) ~[client-1.18.2-20220404.173914-srg.jar%2366!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44) ~[client-1.18.2-20220404.173914-srg.jar%2366!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:138) ~[client-1.18.2-20220404.173914-srg.jar%2366!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by MOMOisha** [comment]
It also keeps crashing for me

**Comment by triphora** [comment]
@KstarMillion Could you confirm the Architectury version you're using?

**Comment by triphora** [comment]
More than two weeks since I asked and no response, going to assume this is resolved...
