### ISSUE TITLE
Problem launching the architectury mod in a server.

### ISSUE THREAD

**Issue by tomycabre** [architectury/architectury#278]
I keep having this error since yesterday and I can't solve it anywhere, there is an specific architectury thing that keeps crashing the server CODE:`[15Jun2022 01:10:07.980] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: class net.minecraftforge.event.world.WorldEvent$Save cannot be cast to class net.minecraftforge.event.world.ChunkDataEvent$Save (net.minecraftforge.event.world.WorldEvent$Save and net.minecraftforge.event.world.ChunkDataEvent$Save are in module forge@41.0.30 of loader 'TRANSFORMER' @64984b0f)
	Index: 1
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/world/WorldEvent$Save;)V
java.lang.ClassCastException: class net.minecraftforge.event.world.WorldEvent$Save cannot be cast to class net.minecraftforge.event.world.ChunkDataEvent$Save (net.minecraftforge.event.world.WorldEvent$Save and net.minecraftforge.event.world.ChunkDataEvent$Save are in module forge@41.0.30 of loader 'TRANSFORMER' @64984b0f)
	at TRANSFORMER/architectury@5.6.21/dev.architectury.event.forge.__EventHandlerImplCommon_event_Save.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.level.ServerLevel.m_8643_(ServerLevel.java:713)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.MinecraftServer.m_129885_(MinecraftServer.java:497)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:576)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.dedicated.DedicatedServer.m_7041_(DedicatedServer.java:521)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:682)
	at TRANSFORMER/minecraft@1.19/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:245)
	at java.base/java.lang.Thread.run(Thread.java:833)

[15Jun2022 01:10:07.980] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Exception stopping the server
java.lang.ClassCastException: class net.minecraftforge.event.world.WorldEvent$Save cannot be cast to class net.minecraftforge.event.world.ChunkDataEvent$Save (net.minecraftforge.event.world.WorldEvent$Save and net.minecraftforge.event.world.ChunkDataEvent$Save are in module forge@41.0.30 of loader 'TRANSFORMER' @64984b0f)
	at dev.architectury.event.forge.__EventHandlerImplCommon_event_Save.invoke(.dynamic) ~[architectury-5.6.21.jar%2348!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93) ~[eventbus-6.0.0.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%232!/:?]
	at net.minecraft.server.level.ServerLevel.m_8643_(ServerLevel.java:713) ~[server-1.19-20220607.102129-srg.jar%2367!/:?]
	at net.minecraft.server.MinecraftServer.m_129885_(MinecraftServer.java:497) ~[server-1.19-20220607.102129-srg.jar%2367!/:?]
	at net.minecraft.server.MinecraftServer.m_7041_(MinecraftServer.java:576) ~[server-1.19-20220607.102129-srg.jar%2367!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7041_(DedicatedServer.java:521) ~[server-1.19-20220607.102129-srg.jar%2367!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:682) ~[server-1.19-20220607.102129-srg.jar%2367!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:245) ~[server-1.19-20220607.102129-srg.jar%2367!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by MaxNeedsSnacks** [comment]
This should've been fixed by #281 hopefully
