### ISSUE TITLE
[1.19] Architectury  might be blocking player messages

### ISSUE THREAD

**Issue by kwpugh** [architectury/architectury#282]
log:  https://paste.ee/p/Ez1aF

when my mod executes this code:
```
playerIn.sendMessage((Text.translatable("item.greater_eye.greater_eye.message1", structureChoice).formatted(Formatting.BOLD)), true);
```

the text doesn't display and the following error shows up  in launcher
```
[11:22:52] [Render thread/ERROR]: Error executing task on Client
java.lang.ClassCastException: class dev.architectury.event.EventResult cannot be cast to class dev.architectury.event.CompoundEventResult (dev.architectury.event.EventResult and dev.architectury.event.CompoundEventResult are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @77b52d12)
	at jdk.proxy2.$Proxy99.process(Unknown Source) ~[?:?]
	at net.minecraft.class_329.localvar$zcl000$modifySystemMessage(class_329.java:1596) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_43591(class_329.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_43596(class_634.java:805) ~[client-intermediary.jar:?]
	at net.minecraft.class_7439.method_43631(class_7439.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_7439.method_11054(class_7439.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1095) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

when I remove Architectury, it works as expected.

**Comment by shedaniel** [comment]
Outdated architectury API
