### ISSUE TITLE
failing to launch 1.17.1 fabric

### ISSUE THREAD

**Issue by sapppho** [architectury/architectury#303]
so i was having trouble launching minecraft, kept on giving me error code 1, so i decided to put mods into my folder one by one, to figure out which one is causing the issue. so i was up to optifine 1.17.1, optifabric 1.12.6, and fabric-api-0.46.1, and everything was going good. but i added architectury-2.10.10 and now im getting error code 1.  im not gonna put my latest logs into this post because its a lot, but ill drop them in the comments below. any help would be appreciated!
(also, worldedit works fine when its alone in the mod folder with fabric api. its optifine and optifabric that are making this problem)

**Comment by sapppho** [comment]
logs (ive bolded what seems important):
[17:22:32] [main/INFO]: Loading Minecraft 1.17.1 with Fabric Loader 0.14.8
[17:22:32] [main/INFO]: Loading 53 mods:
	- architectury 2.10.10
	- fabric 0.46.1+1.17
	- fabric-api-base 0.4.0+cf39a74318 via fabric
	- fabric-api-lookup-api-v1 1.5.0+e821752d18 via fabric
	- fabric-biome-api-v1 3.2.2+cf39a74318 via fabric
	- fabric-blockrenderlayer-v1 1.1.6+cf39a74318 via fabric
	- fabric-command-api-v1 1.1.4+cf39a74318 via fabric
	- fabric-commands-v0 0.2.3+cf39a74318 via fabric
	- fabric-containers-v0 0.1.13+cf39a74318 via fabric
	- fabric-content-registries-v0 0.4.1+3447790d18 via fabric
	- fabric-crash-report-info-v1 0.1.6+cf39a74318 via fabric
	- fabric-dimensions-v1 2.0.15+b556f28c18 via fabric
	- fabric-entity-events-v1 1.4.1+377137cc18 via fabric
	- fabric-events-interaction-v0 0.4.12+e99fbe1218 via fabric
	- fabric-events-lifecycle-v0 0.2.4+cf39a74318 via fabric
	- fabric-game-rule-api-v1 1.0.8+cf39a74318 via fabric
	- fabric-item-api-v1 1.3.0+6617390918 via fabric
	- fabric-item-groups-v0 0.3.2+cf39a74318 via fabric
	- fabric-key-binding-api-v1 1.0.6+2a2bb57318 via fabric
	- fabric-keybindings-v0 0.2.4+cf39a74318 via fabric
	- fabric-lifecycle-events-v1 1.4.6+0392f3a618 via fabric
	- fabric-loot-tables-v1 1.0.5+cf39a74318 via fabric
	- fabric-mining-level-api-v1 1.0.3+cf39a74318 via fabric
	- fabric-mining-levels-v0 0.1.7+cf39a74318 via fabric
	- fabric-models-v0 0.3.1+cf39a74318 via fabric
	- fabric-networking-api-v1 1.0.14+cf39a74318 via fabric
	- fabric-networking-blockentity-v0 0.2.12+cf39a74318 via fabric
	- fabric-networking-v0 0.3.3+cf39a74318 via fabric
	- fabric-object-builder-api-v1 1.11.1+f907116918 via fabric
	- fabric-object-builders-v0 0.7.8+cf39a74318 via fabric
	- fabric-particles-v1 0.2.5+cf39a74318 via fabric
	- fabric-registry-sync-v0 0.8.0+ea29b33318 via fabric
	- fabric-renderer-api-v1 0.4.6+ce16ae5918 via fabric
	- fabric-renderer-indigo 0.4.10+ce16ae5918 via fabric
	- fabric-renderer-registries-v1 3.2.6+cf39a74318 via fabric
	- fabric-rendering-data-attachment-v1 0.1.6+cf39a74318 via fabric
	- fabric-rendering-fluids-v1 0.2.1+cf39a74318 via fabric
	- fabric-rendering-v0 1.1.7+cf39a74318 via fabric
	- fabric-rendering-v1 1.10.1+377137cc18 via fabric
	- fabric-resource-conditions-api-v1 1.0.1+591a0f2118 via fabric
	- fabric-resource-loader-v0 0.4.10+f09604ce18 via fabric
	- fabric-screen-api-v1 1.0.5+cf39a74318 via fabric
	- fabric-screen-handler-api-v1 1.1.9+cf39a74318 via fabric
	- fabric-structure-api-v1 1.2.0+48a9ad8918 via fabric
	- fabric-tag-extensions-v0 1.2.3+cf39a74318 via fabric
	- fabric-textures-v0 1.0.7+cf39a74318 via fabric
	- fabric-tool-attribute-api-v1 1.3.3+3b96517518 via fabric
	- fabric-transfer-api-v1 1.5.4+cf39a74318 via fabric
	- fabricloader 0.14.8
	- java 16
	- minecraft 1.17.1
	- mm 2.3 via optifabric
	- optifabric 1.12.6
[17:22:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/mfbur/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:22:33] [main/INFO]: Compatibility level set to JAVA_16
**[17:22:34] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[17:22:34] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath**
[17:22:35] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
**[17:22:35] [main/ERROR]: Mixin apply for mod (unknown) failed optifabric.compat.architectury-AB.newer-mixins.json:Gamwered.asm.mixin.transformer.throwables.MixinApplicatorException Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.architectury-AB.newer-mixins.json:GameRendererNewerMixin from mod (unknown)]**
org.spongepowered.asm.mixin.transformer.throwables.MixinApplicatorException: Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.architectury-AB.newer-mixins.json:GameRendererNewerMixin from mod (unknown)]eRendererNewerMixin from mod (unknown) -> net.minecraft.class_757: org.spongepowered.asm.mixin.transformer.throwables.MixinApplicatorException Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.architectury-AB.newer-mixins.json:GameRendererNewerMixin from mod (unknown)]
org.spongepowered.asm.mixin.transformer.throwables.MixinApplicatorException: Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.architectury-AB.newer-mixins.json:GameRendererNewerMixin from mod (unknown)]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:358) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) [fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) [?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3229) [?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2335) [?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) [Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:519) [Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) [client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:348) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
**Caused by: java.lang.IllegalArgumentException: Can't find Mixin class dev/architectury/mixin/fabric/client/MixinGameRenderer targetting net.minecraft.class_757**
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.findMixin(InterceptingMixinPlugin.java:90) ~[optifabric-1.12.6%20(1).jar:?]
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.preApply(InterceptingMixinPlugin.java:57) ~[optifabric-1.12.6%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.preApply(PluginHandle.java:158) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.preApply(MixinInfo.java:1358) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.preApply(MixinTargetContext.java:1260) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:313) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	... 21 more
[17:22:35] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:348) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[fabric-loader-0.14.8-1.17.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3229) ~[?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2335) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:519) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:348) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[fabric-loader-0.14.8-1.17.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3229) ~[?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2335) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:519) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:348) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[fabric-loader-0.14.8-1.17.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [optifabric.compat.architectury-AB.newer-mixins.json:GameRendererNewerMixin from mod (unknown)] from phase [DEFAULT] in config [optifabric.compat.architectury-AB.newer-mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3229) ~[?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2335) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:519) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:348) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[fabric-loader-0.14.8-1.17.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinApplicatorException: Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.architectury-AB.newer-mixins.json:GameRendererNewerMixin from mod (unknown)]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:358) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3229) ~[?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2335) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:519) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:348) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[fabric-loader-0.14.8-1.17.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more
Caused by: java.lang.IllegalArgumentException: Can't find Mixin class dev/architectury/mixin/fabric/client/MixinGameRenderer targetting net.minecraft.class_757
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.findMixin(InterceptingMixinPlugin.java:90) ~[optifabric-1.12.6%20(1).jar:?]
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.preApply(InterceptingMixinPlugin.java:57) ~[optifabric-1.12.6%20(1).jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.preApply(PluginHandle.java:158) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.preApply(MixinInfo.java:1358) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.preApply(MixinTargetContext.java:1260) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:313) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3229) ~[?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2335) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:519) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:348) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:137) ~[fabric-loader-0.14.8-1.17.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 2 more

**Comment by triphora** [comment]
OptiFine is not supported, please report to OptiFabric or use the [OptiFine alternatives](https://lambdaurora.dev/optifine_alternatives/)

**Comment by sapppho** [comment]
is this a new development? just last week they were working fine together

**Comment by triphora** [comment]
Dunno, we don't develop OptiFine. OptiFine breaks wayyyyyyyyy too much stuff.
