### ISSUE TITLE
Incompatible mod set (MC 1.19.2 Fabric)

### ISSUE THREAD

**Issue by LilPaws** [architectury/architectury#330]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Architectury' (architectury) 5.12.44 with version 2- or later that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'Architectury' (architectury) 5.12.44 requires version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Juuxel** [comment]
You need to use the 1.19.2 version of Architectury API. You can find it using this tool: https://juuxel.github.io/architectury-api-versions/
