### ISSUE TITLE
Using this module can not send chat messages under the server of multiple people

### ISSUE THREAD

**Issue by aggsyr** [architectury/architectury#413]
1.19.2molist Core Using this mod can not send chat messages under a multi-player server, the terminal is not visible, and other players are not visible

**Comment by MuelsyseKen** [comment]
```
[02:56:06 ERROR]: Exception caught during firing event: net/minecraftforge/event/ServerChatEvent$Submitted
        Index: 1
        Listeners:
                0: HIGH
                1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/ServerChatEvent$Submitted;)V
java.lang.NoClassDefFoundError: net/minecraftforge/event/ServerChatEvent$Submitted
        at dev.architectury.event.forge.__EventHandlerImplCommon_event_Submitted.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:318)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:298)
        at TRANSFORMER/forge@43.2.18/net.minecraftforge.common.ForgeHooks.onServerChatSubmittedEvent(ForgeHooks.java:460)
        at TRANSFORMER/forge@43.2.18/net.minecraftforge.common.ForgeHooks$1.lambda$decorate$0(ForgeHooks.java:473)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.ServerChatEvent$Submitted
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ClassLoaderFactory$ASMClassLoader.loadClass(ClassLoaderFactory.java:110)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 13 more

[02:56:06 ERROR]: Chain link failed, continuing to next one
java.lang.NoClassDefFoundError: net/minecraftforge/event/ServerChatEvent$Submitted
        at dev.architectury.event.forge.__EventHandlerImplCommon_event_Submitted.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:318) ~[eventbus-6.0.5.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:298) ~[eventbus-6.0.5.jar:?]
        at net.minecraftforge.common.ForgeHooks.onServerChatSubmittedEvent(ForgeHooks.java:460) ~[?:?]
        at net.minecraftforge.common.ForgeHooks$1.lambda$decorate$0(ForgeHooks.java:473) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.ServerChatEvent$Submitted
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at net.minecraftforge.eventbus.ClassLoaderFactory$ASMClassLoader.loadClass(ClassLoaderFactory.java:110) ~[eventbus-6.0.5.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 13 more
```

Same Problem in Mohist Server 1.19.2
