### ISSUE TITLE
[1.20.5] architectury crash on neoforge

### ISSUE THREAD

**Issue by st0x0ef** [architectury/architectury#497]
Architectury doesn't load on neoforge since it try to use the ClientTickEvent

CrashLog :
```
Caused by 0: java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/TickEvent$ClientTickEvent
		at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
		at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[?:?] {}
		at java.base/java.lang.Class.getDeclaredMethods(Class.java:2676) ~[?:?] {}
		at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.register(EventBus.java:85) ~[bus-7.2.0.jar%2394!/:?] {}
		at TRANSFORMER/architectury@12.0.26/dev.architectury.event.forge.EventHandlerImpl.registerClient(EventHandlerImpl.java:31) ~[architectury-12.0.26-neoforge.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
		at TRANSFORMER/architectury@12.0.26/dev.architectury.event.EventHandler.registerClient(EventHandler.java) ~[architectury-12.0.26-neoforge.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
		at TRANSFORMER/architectury@12.0.26/dev.architectury.event.EventHandler.init(EventHandler.java:38) ~[architectury-12.0.26-neoforge.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
		at TRANSFORMER/architectury@12.0.26/dev.architectury.neoforge.ArchitecturyNeoForge.<init>(ArchitecturyNeoForge.java:33) ~[architectury-12.0.26-neoforge.jar%23175!/:?] {re:classloading}
		at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
		at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
		at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
		at MC-BOOTSTRAP/fml_loader@3.0.18/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:101) ~[loader-3.0.18.jar%2387!/:3.0] {}
		at MC-BOOTSTRAP/fml_loader@3.0.18/net.neoforged.fml.ModLoader.lambda$constructMods$9(ModLoader.java:169) ~[loader-3.0.18.jar%2387!/:3.0] {}
		at MC-BOOTSTRAP/fml_loader@3.0.18/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$11(ModLoader.java:216) ~[loader-3.0.18.jar%2387!/:3.0] {}
		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}

**Comment by shedaniel** [comment]
Neo have recently pushed a breaking change, it requires an update on our part :/ 
I/someone will get on this tomorrow
