### ISSUE TITLE
Get error while executing `runServer` in modified template codes for mc1.20.6

### ISSUE THREAD

**Issue by sakurawald** [architectury/architectury#505]
I download the `architectury template` codes for `mc1.20.1` and modify the minecraft version to `mc1.20.6` and get errors.

```
> Configure project :
Architect Plugin: 3.4.155
Architectury Loom: 1.6.397
This version of Architectury Loom is in beta! Please report any issues you encounter: https://github.com/architectury/architectury-loom/issues

> Task :common:compileJava UP-TO-DATE
> Task :common:processResources UP-TO-DATE
> Task :common:classes UP-TO-DATE
> Task :common:jar
> Task :forge:compileJava
> Task :forge:processResources
> Task :forge:classes
> Task :forge:generateDLIConfig
> Task :forge:generateLog4jConfig
> Task :forge:generateRemapClasspath UP-TO-DATE
> Task :forge:prepareArchitecturyTransformer
> Task :forge:configureLaunch

> Task :forge:runServer
[Architectury Transformer] Architectury Runtime 5.2.83
[Architectury Transformer] Read classpath in 1.178 s
[Architectury Transformer] Listening at /home/sakurawald/Workspace/github/architectury-example-mod/common/build/devlibs/examplemod-1.0.0-dev.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133)
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53)
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19)
	at juuxel.unionrelauncher.UnionRelauncher.main(UnionRelauncher.java:92)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219)
Caused by: java.lang.module.FindException: Module org.lwjgl.openal not found, required by org.lwjgl.openal.natives
	at java.base/java.lang.module.Resolver.findFail(Resolver.java:892)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:491)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:297)
	at net.minecraftforge.bootstrap@2.1.1/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:166)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 7 more
```

**It's ok to run `fabric` side `runServer`, but `forge` side gets the error.**

**It's also ok to run `fabric` and `forge` side's `runServer` task if the minecraft version is set to `1.20.1`** 

The modified codes are here: 
[modified-template-for-mc1.20.6.zip](https://github.com/architectury/architectury-api/files/15381264/modified-template-for-mc1.20.6.zip)

**Comment by sakurawald** [comment]
The same error in code generated by `Minecraft Development` jetbrain plugin.

**Comment by Fuzss** [comment]
https://github.com/architectury/architectury-loom/issues/191

**Comment by sakurawald** [comment]
> [architectury/architectury-loom#191](https://github.com/architectury/architectury-loom/issues/191)

Thanks for reply, it's the same error.
