### ISSUE TITLE
[1.21] NeoForge - Module fml_loader reads another module named fml_loader

### ISSUE THREAD

**Issue by FlashHUN** [architectury/architectury#543]
Running Architectury + NeoForge with KotlinForForge through IntelliJ IDEA throws the following:
```
Exception in thread "main" java.lang.module.ResolutionException: Module fml_loader reads another module named fml_loader
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:718)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:87)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:90)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219)
```

This line seems out of place, wonder if this is intended behaviour considering I'm trying to run NeoForge:
`at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)`

Fabric with Fabric Language Kotlin runs perfectly fine.

On a previous version (MC 1.20.6, Architectury API 12.1.2, NeoForge 20.6.77-beta, KFF 5.1.0) the project ran perfectly fine, can't figure out whether the issue is with KFF or Architectury so making [an issue for KFF too](https://github.com/thedarkcolour/KotlinForForge/issues/103).

Enabled Platforms: Fabric, NeoForge
Minecraft Version: 1.21
Architectury API Version: 13.0.4
Fabric Loader Version: 0.16.0
Fabric API Version: 0.100.6+1.21
Fabric Language Kotlin Version: 1.11.0+kotlin.2.0.0
NeoForge Version: 21.0.86-beta
KotlinForForge Version: 5.4.0

**Comment by FlashHUN** [comment]
Solved by [excluding KFF's transitive dependency on FancyModLoader](https://github.com/thedarkcolour/KotlinForForge/issues/103#issuecomment-2226420966)
