### ISSUE TITLE
IClientFluidTypeExtension for Neo

### ISSUE THREAD

**Issue by Soaryn** [architectury/architectury#551]
I don't actively use Architectury, so determining to whom would need to be handling this scenario is more of a mystery. However assuming it is the side of the registry API, it seems `IClientFluidTypeExtension` is not initialized for fluids created with Architectury when using `Neo` from my best guess. It is registered via an event now `RegisterClientExtensionsEvent`. The way I handle it for all of my fluids is via a ContentMap that just has reference to all of the fluids I register, instead of me specifying one at a time, but for other systems I have opt-in and opt-out since it is what I need.

```java
    @SubscribeEvent
    private static void initializeClient(RegisterClientExtensionsEvent event) {
        for (XyFluidType fluid : ContentMap.getFluids()) {
            event.registerFluidType(new IClientFluidTypeExtensions() {
                @Override
                public @NotNull ResourceLocation getStillTexture() {
                    return fluid.StillResource;
                }

                @Override
                public @NotNull ResourceLocation getFlowingTexture() {
                    return fluid.FlowingResource;
                }
            }, fluid);
        }
    }
```
As I mentioned, I don't use Architectury, so how it is implemented isn't much of a pain point for me, but there are quite a few mods that seemingly add a fluid with it, that break due to the texture being null incorrectly. If it is up to the modder to register these extensions, you may want to put in some safe guards to inform a dev that they are missing at the very least to try to mitigate the number that slip through.

Example of a mod that has recently come by my issue tracker: https://github.com/st0x0ef/stellaris/issues/17

**Comment by MaxNeedsSnacks** [comment]
I haven't worked on Architectury in a hot minute, but from a cursory glance I found out that the mod doesn't seem to actually register fluid types? This should probably additionally be looked at for this issue, since there is a possibility RegisterClientExtensionsEvent needs them to be registered (and they should be! I'm not sure why they aren't tbh)

**Comment by Bread-NiceCat** [comment]
I have the same issue.
The crash below was caused by placing a extension-unregistered fluid
```
Description: Tesselating liquid in world

java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "pk" is null
	at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328) ~[?:?] {}
	at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242) ~[?:?] {}
	at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097) ~[?:?] {}
	at java.base/java.util.Collections$UnmodifiableMap.getOrDefault(Collections.java:1702) ~[?:?] {}
	at TRANSFORMER/neoforge@21.0.143/net.neoforged.neoforge.client.textures.FluidSpriteCache.getFluidSprites(FluidSpriteCache.java:39) ~[neoforge-21.0.143-minecraft-merged-e582d55c4f-1.21-loom.mappings.1_21.layered+hash.652177077-v2-neoforge-21.0.143.jar%23192!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.block.LiquidBlockRenderer.tesselate(LiquidBlockRenderer.java:74) ~[neoforge-21.0.143-minecraft-merged-e582d55c4f-1.21-loom.mappings.1_21.layered+hash.652177077-v2-neoforge-21.0.143.jar%23191!/:?] {re:classloading,pl:unprotect:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.block.BlockRenderDispatcher.renderLiquid(BlockRenderDispatcher.java:112) ~[neoforge-21.0.143-minecraft-merged-e582d55c4f-1.21-loom.mappings.1_21.layered+hash.652177077-v2-neoforge-21.0.143.jar%23191!/:?] {re:classloading,pl:unprotect:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.chunk.SectionCompiler.compile(SectionCompiler.java:74) ~[neoforge-21.0.143-minecraft-merged-e582d55c4f-1.21-loom.mappings.1_21.layered+hash.652177077-v2-neoforge-21.0.143.jar%23191!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.chunk.SectionRenderDispatcher$RenderSection$RebuildTask.doTask(SectionRenderDispatcher.java:563) ~[neoforge-21.0.143-minecraft-merged-e582d55c4f-1.21-loom.mappings.1_21.layered+hash.652177077-v2-neoforge-21.0.143.jar%23191!/:?] {re:classloading,pl:unprotect:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.chunk.SectionRenderDispatcher.method_22757(SectionRenderDispatcher.java:102) ~[neoforge-21.0.143-minecraft-merged-e582d55c4f-1.21-loom.mappings.1_21.layered+hash.652177077-v2-neoforge-21.0.143.jar%23191!/:?] {re:classloading,pl:unprotect:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.Util.method_37911(Util.java:301) ~[neoforge-21.0.143-minecraft-merged-e582d55c4f-1.21-loom.mappings.1_21.layered+hash.652177077-v2-neoforge-21.0.143.jar%23191!/:?] {re:classloading,pl:unprotect:A}
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073) ~[?:?] {re:computing_frames}
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035) ~[?:?] {re:computing_frames}
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187) ~[?:?] {}

```

**Comment by Bread-NiceCat** [comment]
I wrote an alternative way to plug in Arch's FluidType wrapper Extension.
It works well even in *release* env
```
@EventBusSubscriber(value = Dist.CLIENT, bus = EventBusSubscriber.Bus.MOD)
```
```
@SuppressWarnings("unchecked")
	@SubscribeEvent
	private static void initializeClient(RegisterClientExtensionsEvent event) throws Exception{
		log.info("Init fluid_types...");
		Field mapField = ArchitecturyFlowingFluid.class.getDeclaredField("FLUID_TYPE_MAP");
		mapField.setAccessible(true);
		Map<ArchitecturyFluidAttributes, FluidType> fluid_type_map = (Map<ArchitecturyFluidAttributes, FluidType>) mapField.get(null);
		for (FlowingFluidEntry<?, ?> fluid : CFluids.FLUIDS.values()) {
			try {
				//exec Lazy logic in <init>
				FluidType type = fluid.getSource().get().getFluidType();
				
				Method method = type.getClass().getDeclaredMethod("initializeClient", Consumer.class);
				method.setAccessible(true);
				method.invoke(type, (Consumer<IClientFluidTypeExtensions>) ext -> {
					event.registerFluidType(ext, type);
				});
			} catch (Exception e) {
				log.error("Error during init fluid_type: " + fluid, e);
			}
		}
	}
```

**Comment by KCFindstr** [comment]
Thanks a lot! I had a hard time debugging the fluids working on Fabric but crashing on NeoForge. Hope this bug can get fixed.
