### ISSUE TITLE
Crash with some mods that need architectury (1.21.1, neoforge)

### ISSUE THREAD

**Issue by VaporeonScripts** [architectury/architectury#561]
Thread: Render thread
Stacktrace:
	at TRANSFORMER/architectury@13.0.6/dev.architectury.platform.hooks.EventBusesHooks.lambda$whenAvailable$0(EventBusesHooks.java:34) ~[architectury-13.0.6-neoforge.jar%23562!/:?] {re:classloading}
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
	at TRANSFORMER/architectury@13.0.6/dev.architectury.platform.hooks.EventBusesHooks.whenAvailable(EventBusesHooks.java:34) ~[architectury-13.0.6-neoforge.jar%23562!/:?] {re:classloading}
	at TRANSFORMER/architectury@13.0.6/dev.architectury.networking.forge.NetworkManagerImpl$1.registerS2C(NetworkManagerImpl.java:70) ~[architectury-13.0.6-neoforge.jar%23562!/:?] {re:classloading}
	at TRANSFORMER/architectury@13.0.6/dev.architectury.impl.NetworkAggregator.registerS2CReceiver(NetworkAggregator.java:119) ~[architectury-13.0.6-neoforge.jar%23562!/:?] {re:classloading}
	at TRANSFORMER/architectury@13.0.6/dev.architectury.impl.NetworkAggregator.registerReceiver(NetworkAggregator.java:91) ~[architectury-13.0.6-neoforge.jar%23562!/:?] {re:classloading}
	at TRANSFORMER/architectury@13.0.6/dev.architectury.networking.NetworkManager.registerReceiver(NetworkManager.java:102) ~[architectury-13.0.6-neoforge.jar%23562!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/architectury@13.0.6/dev.architectury.networking.NetworkManager.registerReceiver(NetworkManager.java:97) ~[architectury-13.0.6-neoforge.jar%23562!/:?] {re:mixin,re:classloading}

**Comment by ThexXTURBOXx** [comment]
Duplicate of #527 and #531 (solution is there)

**Comment by VaporeonScripts** [comment]
oh,alright
