### ISSUE TITLE
crash when sprint-swimming (fabric)

### ISSUE THREAD

**Issue by JSJBDEV** [architectury/architectury#66]
```
net.minecraft.class_148: Ticking player
	at net.minecraft.class_3222.method_14226(class_3222.java:498) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:219) ~[intermediary-server.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:232) ~[intermediary-server.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:173) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void me.shedaniel.architectury.networking.NetworkChannel.sendToServer(java.lang.Object)'
	at net.minecraft.class_1657.handler$ccp000$updateAirSwimming(class_1657.java:15874) ~[intermediary-server.jar:?]
	at net.minecraft.class_1657.method_5790(class_1657.java:1581) ~[intermediary-server.jar:?]
	at net.minecraft.class_1297.method_5670(class_1297.java:458) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_5670(class_1309.java:324) ~[intermediary-server.jar:?]
	at net.minecraft.class_1297.method_5773(class_1297.java:431) ~[intermediary-server.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2209) ~[intermediary-server.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[intermediary-server.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:434) ~[intermediary-server.jar:?]
	... 9 more
```

this only happens serverside running architectury-1.10.138-fabric it forcefully disconnects a player when they start sprint-swimming

**Comment by MaxNeedsSnacks** [comment]
I'll need a bit more info:
- What other mods do you have in your pack, notably mods *using* architectury API
- Can you please give me a ***full*** crash log rather than an incomplete snippet, if possible please try adding Not Enough Crashes and Blame to make finding the culprit easier

**Comment by JSJBDEV** [comment]
alright will do

**Comment by JSJBDEV** [comment]
One thing I will say is a real crashlog is not generated since the server simply kicks the player for the above reason, I can give you a full server log but I dont think there is any more useful information for you, so I shall get a list of mods and use the above mods just in case the also do with forceful disconnects

**Comment by JSJBDEV** [comment]
So I tried doing all the steps again and the best we get is the above log on the server and then everything continues as normal. so I think the only bet we have is finding the architectuary reliant mod that causes it

**Comment by MaxNeedsSnacks** [comment]
Figured this out, this one's actually on you / adox :p 

https://github.com/JSJBDEV/Aquarius/blob/56d59750c66efc0bbdf5707c20f10ed3d8048414/fabric/src/main/java/space/bbkr/aquarius/fabric/mixin/MixinPlayerEntity.java#L110

**Comment by JSJBDEV** [comment]
And would you believe It Ive found the culprit and ironically It is a mod I maintain, Aquarius - one of the authors switched to architectury to port to forge and appears to have broken something. Thank you for your time Ill get that sorted now just in case

**Comment by JSJBDEV** [comment]
oh snap

**Comment by JSJBDEV** [comment]
I actually havent touched the mod since it was switched to architectury so any suggestions so I can just fix it myself?

**Comment by JSJBDEV** [comment]
I will close this now and get adox to fix it, but if you have any ideas Ill take em xD

**Comment by MaxNeedsSnacks** [comment]
Well, that message is client-to-server, so I don't understand why it's being sent in that block (which fires on the server side if the player was swimming last tick, which is *not* how it should be)

I'm assuming this was a bracket issue, as the code makes sense if you just move it up a line
![image](https://user-images.githubusercontent.com/12750501/113520530-00707300-9594-11eb-8f98-ad3dcff89bb8.png)

**Comment by JSJBDEV** [comment]
No worries Ill get it fixed, sorry for taking your time, didnt realise till you mentioned it that it was another mod

**Comment by MaxNeedsSnacks** [comment]
Absolutely no worries! If it does turn out to be an issue with architectury, feel free to reopen as well!

**Comment by JSJBDEV** [comment]
ive moved the line, will build and test it
